#!/usr/bin/env python3
"""Embed git metadata into the MicroPython build."""
import argparse
import pathlib
import subprocess
from typing import Tuple

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "git_info.py"


def git(cmd: Tuple[str, ...]) -> str:
    try:
        return subprocess.check_output(cmd, cwd=ROOT).decode().strip()
    except Exception:
        return "unknown"


def get_git_metadata():
    repo = git(("git", "config", "--get", "remote.origin.url"))
    branch = git(("git", "rev-parse", "--abbrev-ref", "HEAD"))
    commit = git(("git", "rev-parse", "HEAD"))
    short_commit = git(("git", "rev-parse", "--short", "HEAD"))
    return repo, branch, commit, short_commit


def write_module(path: pathlib.Path, repo: str, branch: str, commit: str, short: str) -> None:
    content = f"""# Auto-generated by tools/embed_git_info.py\nREPOSITORY = {repo!r}\nBRANCH = {branch!r}\nCOMMIT = {commit!r}\nSHORT_COMMIT = {short!r}\n"""
    path.write_text(content)


def main():
    parser = argparse.ArgumentParser(description="Embed git metadata")
    parser.add_argument("--output", type=pathlib.Path, default=SRC, help="Path to git_info.py")
    args = parser.parse_args()

    repo, branch, commit, short_commit = get_git_metadata()
    write_module(args.output, repo, branch, commit, short_commit)


if __name__ == "__main__":
    main()
